### PR TITLE
CallChain: Better support for class namespaces in GUI and DOT representation

### PR DESCRIPTION
**Pull request by v-p-b**
When working with programs with class namespaces it's more convenient to order the lists on the GUI based on the fully qualified names of the function, that include the class namespace too. 

Extending this to graphing is a bit problematic, because colons have a special meaning Graphviz, so putting "SomeClass::someFunc()" in the graph will produce weird results. I also introduced a function name sanitizer to handle this.

### CODE REVIEW

**Comment by fuzzywalls** [comment]
@v-p-b Work has suddenly gotten very busy, but I will try and test this soon. In the meantime, would you please add comments to the `sanitize_dot` function similar to the other functions in that file? Thanks!

**Review by fuzzywalls — CHANGES_REQUESTED** [review]
I did a little testing and it seems like `dot.node` function cant handle the : character in the first parameter which is the unique identifier. The second parameter is the label and that is what is displayed in the bubble graph, this parameter can handle the ":" parameter. Changing the `dot.node` function calls to `dot.node(function_name, str(function), ...)` seems to fix the problem while still presenting the '::' in the graph. 
Screen Shot 2020-03-02 at 4 05 37 PM

**Comment by v-p-b** [comment]
Thank, this is useful info, I'll update the PR probably later today.

**Review by fuzzywalls — APPROVED** [review]

**Comment by fuzzywalls** [comment]
Tested and merged. Thanks for the fix @v-p-b!

**Pull request merged**
