### PR TITLE
rizzo: Fix incorrect trimming of hex() result

### PR DESCRIPTION
**Pull request by VelocityRa**
Relevant issue: #16

### CODE REVIEW

**Comment by VelocityRa** [comment]
This fixed an issue where I only got ~100 matches in a project whereas I expected more.
With the fix I got ~900.

Ghidra version: 9.2.2

**Review by fuzzywalls — CHANGES_REQUESTED** [review]
See comments on issue #16, need to account for the 'L' at then end of the string.

Something like this:

```
addr_hex = hex(curr_func.address)
if addr_hex.endswith('L'):
    addr_hex = addr_hex[:-1]
curr_addr = self._address_factory.getAddress(addr_hex)
```

**Comment by VelocityRa** [comment]
Makes sense.
Should be good now. Thanks :)

**Comment by fuzzywalls** [comment]
Thanks @VelocityRa, appreciate the find and the fix.

**Pull request merged**
